export type Role = "CUSTOMER" | "MECHANIC" | "MANAGER" | "ADMIN";
export type RequestStatus =
  | "DRAFT" | "SEARCHING" | "ASSIGNED" | "ACCEPTED" | "EN_ROUTE" | "ARRIVED"
  | "INSPECTING" | "QUOTE_SENT" | "QUOTE_APPROVED" | "REPAIRING" | "PAYMENT_PENDING"
  | "PAYMENT_FAILED" | "COMPLETED" | "QUOTE_REJECTED" | "CANCELLED_BY_CUSTOMER"
  | "CANCELLED_BY_MECHANIC" | "CANCELLED_BY_MANAGER" | "NO_MECHANIC_AVAILABLE" | "DISPUTED";

export const roles = ["CUSTOMER", "MECHANIC", "MANAGER", "ADMIN"] as const;
export const requestStatuses = [
  "DRAFT", "SEARCHING", "ASSIGNED", "ACCEPTED", "EN_ROUTE", "ARRIVED", "INSPECTING",
  "QUOTE_SENT", "QUOTE_APPROVED", "REPAIRING", "PAYMENT_PENDING", "PAYMENT_FAILED",
  "COMPLETED", "QUOTE_REJECTED", "CANCELLED_BY_CUSTOMER", "CANCELLED_BY_MECHANIC",
  "CANCELLED_BY_MANAGER", "NO_MECHANIC_AVAILABLE", "DISPUTED"
] as const;
