"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { BatteryCharging, Bell, Car, ChevronRight, CircleHelp, Disc3, Fuel, Gauge, History, LifeBuoy, MapPin, Settings, ShieldCheck, UserRound, Wrench } from "lucide-react";
import { Nav, Shell } from "@/components/ui";
import { endpoints } from "@/lib/api";
import { useAuthStore } from "@/lib/auth-store";
import type { ServiceRequest, Vehicle } from "@/types/api";

const TrackingMap = dynamic(() => import("@/components/tracking-map"), { ssr: false, loading: () => <div className="h-full min-h-[280px] animate-pulse rounded-xl bg-zinc-200 dark:bg-panel" /> });
const services = [["Battery jump start", "battery issue", BatteryCharging], ["Flat tyre", "flat tyre", Disc3], ["Engine trouble", "engine problem", Wrench], ["Towing", "towing request", Car], ["Fuel delivery", "fuel problem", Fuel], ["Overheating", "overheating", Gauge], ["Electrical problem", "electrical fault", Settings], ["Other assistance", "other", CircleHelp]] as const;
const statusLabels: Record<string, string> = { SEARCHING: "Finding the best technician nearby", ASSIGNED: "Technician assigned", ACCEPTED: "Your technician accepted the request", EN_ROUTE: "Your technician is on the way", ARRIVED: "Your technician has arrived", INSPECTING: "Your vehicle is being inspected", QUOTE_SENT: "Your quotation is ready", QUOTE_APPROVED: "Quotation approved", REPAIRING: "Repair in progress", PAYMENT_PENDING: "Payment is ready", COMPLETED: "Service completed", NO_MECHANIC_AVAILABLE: "We are still looking for help" };
const progress = ["SEARCHING", "ASSIGNED", "EN_ROUTE", "ARRIVED", "INSPECTING", "REPAIRING", "COMPLETED"];

export default function DashboardPage() {
  const user = useAuthStore((state) => state.user);
  const vehicles = useQuery({ queryKey: ["vehicles"], queryFn: () => endpoints.vehicles().then((response) => response.data.data) });
  const requests = useQuery({ queryKey: ["requests"], queryFn: () => endpoints.requests().then((response) => response.data.data.items) });
  const [location, setLocation] = useState<[number, number] | null>(null);
  const [locationState, setLocationState] = useState<"idle" | "loading" | "ready" | "denied">("idle");
  const active = requests.data?.find((request) => !["COMPLETED", "CANCELLED_BY_CUSTOMER", "CANCELLED_BY_MECHANIC", "CANCELLED_BY_MANAGER"].includes(request.currentStatus));
  const selectedVehicle = active?.vehicle || vehicles.data?.[0];

  function detectLocation() {
    if (!navigator.geolocation) { setLocationState("denied"); return; }
    setLocationState("loading");
    navigator.geolocation.getCurrentPosition((position) => { setLocation([position.coords.longitude, position.coords.latitude]); setLocationState("ready"); }, () => setLocationState("denied"));
  }

  useEffect(() => { if (active?.breakdownLocation?.coordinates) setLocation(active.breakdownLocation.coordinates); }, [active]);

  return <Shell><Nav /><main className="mx-auto max-w-7xl px-4 pb-24 pt-6 sm:px-6 lg:px-8 lg:pb-10">
    <div className="mb-7 flex items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-engine-red">EngineX Rescue Pulse</p><h1 className="mt-2 font-display text-4xl font-bold leading-none tracking-tight sm:text-5xl">Wherever the road stops,<br /><span className="text-zinc-400 dark:text-metallic">EngineX keeps you moving.</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-600 dark:text-metallic sm:text-base" suppressHydrationWarning>Good {getTimeOfDay()}, {user?.name?.split(" ")[0] || "driver"}. Request trusted roadside help, track your technician live and get back on the road with confidence.</p></div><div className="hidden items-center gap-2 text-sm text-zinc-500 dark:text-metallic sm:flex"><Bell size={18} /> Support is available 24/7</div></div>
    <section className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="relative overflow-hidden rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-panel sm:p-7"><div className="absolute -right-24 -top-24 size-64 rounded-full bg-engine-red/10 blur-3xl" />{active ? <ActiveRescue request={active} /> : <div className="relative flex min-h-[290px] flex-col justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-600 dark:text-emerald-400"><span className="size-2 animate-pulse rounded-full bg-emerald-500" /> Help is nearby</div><h2 className="mt-5 font-display text-3xl font-bold">Ready when the road is not.</h2><p className="mt-2 max-w-md text-sm text-zinc-600 dark:text-metallic">Share your location and request a verified technician. You stay in control until you confirm the request.</p></div><div className="flex flex-col items-center gap-4 sm:flex-row"><Link href="/request" className="rescue-pulse focus-ring inline-flex size-36 shrink-0 items-center justify-center rounded-full bg-action-red text-center font-display text-xl font-bold leading-none text-white shadow-red"><span>GET HELP<br />NOW</span></Link><div className="grid gap-2 text-sm text-zinc-600 dark:text-metallic"><p className="flex items-center gap-2"><MapPin size={17} className="text-engine-red" /> {locationState === "ready" ? "Your location is ready" : "Location ready when you are"}</p><p className="flex items-center gap-2"><ShieldCheck size={17} className="text-emerald-500" /> Verified technicians and transparent quotes</p></div></div></div>}</div><LocationCard location={location} locationState={locationState} address={active?.address} onDetect={detectLocation} active={Boolean(active)} /></section>
    <TrustRow /><section className="mt-8"><SectionHeading title="What do you need help with?" link="See all services" href="/request" /><div className="quick-services mt-4 flex gap-3 overflow-x-auto pb-2 lg:grid lg:grid-cols-4 lg:overflow-visible">{services.map(([label, category, Icon]) => <Link key={label} href={`/request?service=${encodeURIComponent(category)}`} aria-label={`Request ${label}`} className="service-tile group"><span className="flex size-11 items-center justify-center rounded-md bg-engine-red/10 text-engine-red transition-colors group-hover:bg-engine-red group-hover:text-white"><Icon size={22} /></span><span><strong className="block text-sm">{label}</strong><small className="mt-1 block text-xs text-zinc-500 dark:text-metallic">Get help fast</small></span></Link>)}</div></section>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section><SectionHeading title={active ? "Your active rescue" : "You are all clear"} link={active ? "Open tracking" : "View activity"} href={active ? `/tracking/${active._id}` : "/history"} /><div className="mt-4 rounded-xl border border-zinc-200 bg-white p-5 dark:border-white/10 dark:bg-panel">{active ? <ActiveRequestSummary request={active} /> : <div className="flex items-center justify-between gap-4"><div><p className="font-display text-2xl font-bold">No active roadside requests right now.</p><p className="mt-1 text-sm text-zinc-500 dark:text-metallic">Your next journey starts with a vehicle that is ready to go.</p></div><Link href="/request" className="hidden rounded-md bg-action-red px-4 py-3 text-sm font-bold text-white sm:inline-flex"><LifeBuoy size={17} /> Get help</Link></div>}</div></section><GarageCard vehicle={selectedVehicle} loading={vehicles.isLoading} /></div>
    <RecentActivity requests={requests.data?.filter((request) => request !== active).slice(0, 3) || []} loading={requests.isLoading} /><MobileBottomNav />
  </main></Shell>;
}

function getTimeOfDay() { const hour = new Date().getHours(); return hour < 12 ? "morning" : hour < 18 ? "afternoon" : "evening"; }
function ActiveRescue({ request }: { request: ServiceRequest }) { return <div className="relative min-h-[290px]"><div className="flex items-center justify-between gap-3"><div className="inline-flex items-center gap-2 rounded-full bg-engine-red/10 px-3 py-1 text-xs font-bold text-engine-red"><span className="size-2 animate-pulse rounded-full bg-engine-red" /> Live rescue</div><span className="text-xs text-zinc-500 dark:text-metallic">Request #{request._id.slice(-6).toUpperCase()}</span></div><h2 className="mt-6 font-display text-3xl font-bold">{statusLabels[request.currentStatus] || "Your rescue is in progress"}</h2><p className="mt-2 text-sm text-zinc-600 dark:text-metallic">{request.problemCategory} at {request.address}</p><div className="mt-8 flex items-end gap-8"><div><p className="font-display text-5xl font-bold text-engine-red">{request.estimatedArrivalMinutes != null ? `${request.estimatedArrivalMinutes}m` : "--"}</p><p className="text-xs text-zinc-500 dark:text-metallic">estimated arrival</p></div><div><p className="font-display text-3xl font-bold">{request.estimatedDistanceKm != null ? `${request.estimatedDistanceKm} km` : "--"}</p><p className="text-xs text-zinc-500 dark:text-metallic">distance away</p></div></div><Link href={`/tracking/${request._id}`} className="mt-7 inline-flex min-h-11 items-center gap-2 rounded-md bg-action-red px-5 py-3 text-sm font-bold text-white shadow-red"><MapPin size={17} /> Open live tracking</Link></div>; }
function LocationCard({ location, locationState, address, onDetect, active }: { location: [number, number] | null; locationState: string; address?: string; onDetect: () => void; active: boolean }) { return <div className="location-card relative min-h-[290px] overflow-hidden rounded-2xl border border-zinc-200 bg-zinc-100 dark:border-white/10 dark:bg-[#10151b]">{location ? <TrackingMap customer={location} /> : <div className="relative flex min-h-[290px] flex-col items-center justify-center p-6 text-center"><div className="mb-4 flex size-14 items-center justify-center rounded-full bg-engine-red/10 text-engine-red"><MapPin size={27} /></div><p className="font-semibold">{active ? address || "Rescue location" : locationState === "denied" ? "Location permission is off" : locationState === "loading" ? "Finding your location..." : "Your location is not shared"}</p><p className="mt-2 max-w-xs text-xs text-zinc-500 dark:text-metallic">{active ? "Your request location is shown here." : "Allow location access to see a live map and help us find the nearest technician."}</p>{!active ? <button type="button" onClick={onDetect} className="focus-ring mt-5 inline-flex min-h-11 items-center gap-2 rounded-md bg-action-red px-4 py-2 text-sm font-bold text-white"><MapPin size={17} /> {locationState === "denied" ? "Try location again" : "Use my location"}</button> : null}</div>}{location ? <div className="absolute left-4 top-4 rounded-md bg-white/90 px-3 py-2 text-xs font-semibold shadow dark:bg-asphalt/90"><MapPin size={14} className="mr-1 inline text-engine-red" /> {address || "Current location"}</div> : null}</div>; }
function TrustRow() { return <div className="mt-5 grid grid-cols-2 gap-3 border-y border-zinc-200 py-4 text-xs text-zinc-600 dark:border-white/10 dark:text-metallic sm:grid-cols-4"><span className="flex items-center gap-2"><ShieldCheck size={16} className="text-emerald-500" /> 24/7 assistance</span><span className="flex items-center gap-2"><UserRound size={16} className="text-engine-red" /> Verified technicians</span><span className="flex items-center gap-2"><MapPin size={16} className="text-sky-500" /> Live tracking</span><span className="flex items-center gap-2"><Settings size={16} className="text-zinc-500" /> Transparent quotes</span></div>; }
function SectionHeading({ title, link, href }: { title: string; link: string; href: string }) { return <div className="flex items-center justify-between gap-3"><h2 className="font-display text-2xl font-bold">{title}</h2><Link href={href} className="inline-flex items-center gap-1 text-sm font-semibold text-engine-red">{link}<ChevronRight size={16} /></Link></div>; }
function ActiveRequestSummary({ request }: { request: ServiceRequest }) { const current = progress.indexOf(request.currentStatus); return <div><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="rounded-md bg-engine-red px-2 py-1 text-xs font-bold text-white">{statusLabels[request.currentStatus] || "In progress"}</span><p className="mt-3 font-semibold">{request.vehicle?.registrationNumber} · {request.problemCategory}</p></div>{request.assignedMechanic ? <p className="text-sm text-zinc-500 dark:text-metallic">{request.assignedMechanic.name}</p> : null}</div><div className="mt-6 grid grid-cols-4 gap-1 sm:grid-cols-7">{progress.map((stage, index) => <div key={stage} className="text-center"><span className={`mx-auto block size-3 rounded-full ${index < current ? "bg-emerald-500" : index === current ? "bg-engine-red ring-4 ring-engine-red/20" : "bg-zinc-300 dark:bg-zinc-700"}`} /><span className="mt-2 hidden text-[10px] text-zinc-500 dark:text-metallic sm:block">{stage === "SEARCHING" ? "Received" : stage === "EN_ROUTE" ? "On the way" : stage.charAt(0) + stage.slice(1).toLowerCase()}</span></div>)}</div></div>; }
function GarageCard({ vehicle, loading }: { vehicle?: Vehicle; loading: boolean }) { return <section><SectionHeading title="My garage" link="Manage vehicles" href="/vehicles" /><div className="mt-4 rounded-xl border border-zinc-200 bg-white p-5 dark:border-white/10 dark:bg-panel">{loading ? <div className="h-24 animate-pulse rounded-md bg-zinc-100 dark:bg-asphalt" /> : vehicle ? <div className="flex items-center gap-4"><div className="flex size-16 items-center justify-center rounded-xl bg-zinc-100 text-zinc-500 dark:bg-asphalt dark:text-metallic"><Car size={31} /></div><div className="min-w-0"><p className="font-display text-2xl font-bold">{vehicle.registrationNumber}</p><p className="truncate text-sm text-zinc-500 dark:text-metallic">{vehicle.make} {vehicle.model} · {vehicle.manufactureYear}</p><p className="mt-1 text-xs uppercase tracking-wide text-zinc-400">{vehicle.fuelType} · {vehicle.vehicleType}</p></div></div> : <div><p className="font-semibold">Your garage is empty</p><p className="mt-1 text-sm text-zinc-500 dark:text-metallic">Add a vehicle to request help faster.</p><Link href="/vehicles" className="mt-4 inline-flex min-h-11 items-center rounded-md bg-action-red px-4 py-2 text-sm font-bold text-white">Add a vehicle</Link></div>}</div></section>; }
function RecentActivity({ requests, loading }: { requests: ServiceRequest[]; loading: boolean }) { return <section className="mt-8"><SectionHeading title="Recent activity" link="View all" href="/history" /><div className="mt-4 grid gap-2">{loading ? <div className="h-16 animate-pulse rounded-xl bg-zinc-200 dark:bg-panel" /> : requests.length ? requests.map((request) => <Link href={`/tracking/${request._id}`} key={request._id} className="flex items-center justify-between gap-3 rounded-xl border border-zinc-200 bg-white p-4 transition hover:-translate-y-0.5 hover:shadow-md dark:border-white/10 dark:bg-panel"><span className="flex min-w-0 items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-md bg-engine-red/10 text-engine-red"><History size={18} /></span><span className="min-w-0"><strong className="block truncate text-sm">{request.problemCategory}</strong><small className="text-xs text-zinc-500 dark:text-metallic">{request.vehicle?.registrationNumber} · {request.currentStatus === "COMPLETED" ? "Completed" : "In progress"}</small></span></span><ChevronRight size={18} className="shrink-0 text-zinc-400" /></Link>) : <div className="rounded-xl border border-dashed border-zinc-300 p-6 text-center text-sm text-zinc-500 dark:border-white/10 dark:text-metallic">Your completed services will appear here.</div>}</div></section>; }
function MobileBottomNav() { return <nav className="fixed bottom-0 left-0 right-0 z-40 grid grid-cols-5 border-t border-zinc-200 bg-white/95 px-2 pb-[env(safe-area-inset-bottom)] pt-2 backdrop-blur dark:border-white/10 dark:bg-panel/95"><BottomLink href="/dashboard" icon={LifeBuoy} label="Home" /><BottomLink href="/vehicles" icon={Car} label="Vehicles" /><Link href="/request" className="-mt-6 flex flex-col items-center gap-1 text-[11px] font-bold text-white"><span className="flex size-14 items-center justify-center rounded-full bg-action-red shadow-red"><LifeBuoy size={24} /></span>Help</Link><BottomLink href="/history" icon={History} label="Activity" /><BottomLink href="/profile" icon={UserRound} label="Profile" /></nav>; }
function BottomLink({ href, icon: Icon, label }: { href: string; icon: typeof LifeBuoy; label: string }) { return <Link href={href} className="flex min-h-11 flex-col items-center gap-1 py-1 text-[11px] font-semibold text-zinc-500 dark:text-metallic"><Icon size={19} />{label}</Link>; }